# Generated by Django 3.1.1 on 2020-09-24 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_inseguro',
            new_name='UserInseguro',
        ),
    ]
